version: '3'
services:
  directus:
    build:
      
      dockerfile: Dockerfile
    container_name: projectnoor-directus
    ports:
      - "8055:8055"
    volumes:
      - ./data:/app/data 
      - ./uploads:/app/uploads
      - ./extensions:/app/extensions
    environment:
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/data/niksdb.db"
      ADMIN_EMAIL: "admin@project-noor.eu"
      ADMIN_PASSWORD: "Frikadell3"
